In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from scipy.stats import spearmanr
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
train_data = pd.read_csv('../datasets/titanic_challenge/train.csv')
test_data = pd.read_csv('../datasets/titanic_challenge/test.csv')

In [3]:
corr = train_data.corr()
corr.style.background_gradient(cmap='coolwarm')

In [4]:
lb = LabelEncoder()

train_data_manipulation = train_data.copy()
test_data_manipulation = test_data.copy()

train_data_manipulation['Sex'] = lb.fit_transform(train_data_manipulation['Sex'])
test_data_manipulation['Sex'] = lb.fit_transform(test_data_manipulation['Sex'])

In [5]:
train_data_manipulation.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",0,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",1,35.0,0,0,373450,8.0500,NaN,S

In [6]:
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
corr = train_data_manipulation.corr()
corr.style.background_gradient(cmap='coolwarm')

In [8]:
y = train_data_manipulation['Survived']

features = ['Sex', 'Parch', 'Fare', 'SibSp']

X = train_data_manipulation[features]
X_validation = test_data_manipulation[features]

In [9]:
X_validation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Sex     418 non-null    int32
 1   Parch   418 non-null    int64
 2   Fare    417 non-null    float64
 3   SibSp   418 non-null    int64
dtypes: float64(1), int32(1), int64(2)
memory usage: 11.6 KB

In [10]:
X_validation.fillna(X_validation.median(), inplace=True)

C:\Users\dougl\AppData\Local\Temp\ipykernel_5736\709877469.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_validation.fillna(X_validation.median(), inplace=True)

In [11]:
X_validation.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Sex     418 non-null    int32
 1   Parch   418 non-null    int64
 2   Fare    418 non-null    float64
 3   SibSp   418 non-null    int64
dtypes: float64(1), int32(1), int64(2)
memory usage: 11.6 KB

In [12]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Sex     891 non-null    int32
 1   Parch   891 non-null    int64
 2   Fare    891 non-null    float64
 3   SibSp   891 non-null    int64
dtypes: float64(1), int32(1), int64(2)
memory usage: 24.5 KB

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=38)

In [15]:
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.fit_transform(X_test)
X_validatiion = sc.fit_transform(X_validation)

X_scaled = sc.fit_transform(X)

In [16]:
X_train_scaled

array([[-1.36783323, -0.4881356 , -0.47862791, -0.47998122],
       [ 0.73108328, -0.4881356 , -0.47663989,  0.43869251],
       [ 0.73108328, -0.4881356 , -0.50255673, -0.47998122],
       ...,
       [-1.36783323, -0.4881356 , -0.13043711,  0.43869251],
       [ 0.73108328, -0.4881356 , -0.50366903, -0.47998122],
       [-1.36783323,  2.03036111, -0.37846344, -0.47998122]])

In [17]:
from sklearn import svm

In [ ]:
for i in range (1, 100):
  for j in range(1, 100):
    
    c = i
    gamma = j / 100
    
    model = svm.SVC(C=c, gamma=gamma, random_state=42)
    
    model.fit(X_train_scaled, y_train)
    
    train_preds = model.predict(X_train_scaled)
    test_preds = model.predict(X_test_scaled)
    
    SVM_dic_metrics = {'train_accuracy_score': np.round(accuracy_score(train_preds, y_train), decimals=3) * 100,
                   'test_accuracy_score': np.round(accuracy_score(test_preds, y_test), decimals=3) * 100}

    if(SVM_dic_metrics['train_accuracy_score'] >= 82 and SVM_dic_metrics['test_accuracy_score'] >= 82):
      print("C = {0}, gamma = {1}, train_accuracy = {2}, test_accuracy = {3} ".format(i, gamma, SVM_dic_metrics['train_accuracy_score'], SVM_dic_metrics['test_accuracy_score']))

C = 5, gamma = 0.44, train_accuracy = 82.0, test_accuracy = 83.2
C = 5, gamma = 0.45, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 5, gamma = 0.46, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 5, gamma = 0.47, train_accuracy = 82.0, test_accuracy = 82.1
C = 5, gamma = 0.48, train_accuracy = 82.0, test_accuracy = 82.1
C = 6, gamma = 0.37, train_accuracy = 82.0, test_accuracy = 83.2
C = 6, gamma = 0.38, train_accuracy = 82.0, test_accuracy = 83.2
C = 6, gamma = 0.39, train_accuracy = 82.0, test_accuracy = 83.2
C = 6, gamma = 0.4, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 6, gamma = 0.41, train_accuracy = 82.0, test_accuracy = 82.1
C = 6, gamma = 0.42, train_accuracy = 82.0, test_accuracy = 82.1
C = 6, gamma = 0.43, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 6, gamma = 0.44, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 6, gamma = 0.45, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 6, gamma = 0.46, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 7, gamma = 0.34, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 7, gamma = 0.35, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 7, gamma = 0.37, train_accuracy = 82.0, test_accuracy = 83.2
C = 7, gamma = 0.38, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 7, gamma = 0.39, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 7, gamma = 0.4, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 7, gamma = 0.41, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 8, gamma = 0.36, train_accuracy = 82.0, test_accuracy = 82.69999999999999
C = 8, gamma = 0.37, train_accuracy = 82.0, test_accuracy = 82.69999999999999

In [19]:
# C = 5, gamma = 0.44, train_accuracy = 82.0, test_accuracy = 83.2 

model = svm.SVC(C=5, gamma=0.44)
model.fit(X_scaled, y)

SVC(C=5, gamma=0.44)

In [20]:
predictions = model.predict(X_validatiion)

In [21]:
output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('submission.csv', index=False)